version: "3.7"

services:
  webapp:
    build:
      context: .
      args:
        user: ${USER}
    container_name: js-laravel-mix-starter-kit
    env_file: .docker-env
    volumes:
       - $PWD/src:/home/${USER}/src
    networks:
      jlmsk_net:
        ipv4_address: 192.28.1.1
    command: npm run watch

networks:
    jlmsk_net:
        ipam:
            driver: default
            config:
                - subnet: 192.28.0.0/16
